/**
 * Dados iniciais das empresas da Holding — Sprint 2.
 * Executar via: pnpm --filter @omnia/admin seed
 * Papéis e URLs alinhados a S03_MULTISITE_BRANDING.
 */
export const holdingCompaniesSeed = [
  {
    name: 'Omnia Frigo Holding',
    slug: 'omnia-frigo-holding',
    portalSlug: 'omnia',
    shortDescription: 'Holding estratégica do ecossistema Omnia Frigo.',
    ecosystemRole: 'Holding',
    displayOrder: 1,
    externalSite: 'https://omniafrigo.com.br',
    status: 'active' as const,
    isHolding: true,
    showInEcosystem: false,
    brandTheme: 'omnia' as const,
  },
  {
    name: 'Renovação Refrigeração',
    slug: 'renovacao-refrigeracao',
    portalSlug: 'renovacao',
    shortDescription: 'Engenharia, projetos, instalação e manutenção em refrigeração.',
    ecosystemRole: 'Engenharia',
    displayOrder: 2,
    externalSite: 'https://renovacaorefrigeracao.com.br',
    status: 'active' as const,
    showInEcosystem: true,
    brandTheme: 'renovacao' as const,
  },
  {
    name: 'Neurofrigo Command IA',
    slug: 'neurofrigo',
    portalSlug: 'neurofrigo',
    shortDescription: 'Automação, dados e IA aplicada à refrigeração.',
    ecosystemRole: 'Tecnologia',
    displayOrder: 3,
    externalSite: 'https://neurofrigo.com.br',
    status: 'active' as const,
    showInEcosystem: true,
    brandTheme: 'neurofrigo' as const,
  },
  {
    name: 'Fred do Frio',
    slug: 'fred-do-frio-academy',
    portalSlug: 'fred-do-frio',
    shortDescription: 'Educação moderna e especialização em refrigeração.',
    ecosystemRole: 'Educação',
    displayOrder: 4,
    externalSite: 'https://freddofrio.com.br',
    status: 'active' as const,
    showInEcosystem: true,
    brandTheme: 'fred' as const,
  },
  {
    name: 'CTE',
    slug: 'cte',
    portalSlug: 'cte',
    shortDescription: 'Formação técnica, normativa e industrial.',
    ecosystemRole: 'Formação Técnica',
    displayOrder: 5,
    externalSite: 'https://escolacte.com.br',
    status: 'active' as const,
    showInEcosystem: true,
    brandTheme: 'cte' as const,
  },
  {
    name: 'Centro Educacional Sapientia',
    slug: 'centro-educacional-sapientia',
    portalSlug: 'sapientia',
    shortDescription: 'Instituição educacional parceira do ecossistema Omnia.',
    ecosystemRole: 'Educação',
    displayOrder: 6,
    externalSite: 'https://centroeducacionalsapientia.com.br',
    status: 'active' as const,
    showInEcosystem: false,
    brandTheme: 'omnia' as const,
  },
  {
    name: 'Neurofrigo Carga',
    slug: 'neurofrigo-carga',
    portalSlug: 'neurofrigo-carga',
    shortDescription: 'Aplicativo de carga e logística para a cadeia do frio.',
    ecosystemRole: 'Produto',
    displayOrder: 7,
    externalSite: null,
    applicationUrl: null,
    status: 'active' as const,
    showInEcosystem: true,
    brandTheme: 'neurofrigo' as const,
  },
];

export const defaultTenantSeed = {
  name: 'Omnia Frigo Holding',
  slug: 'omnia-holding',
  description: 'Tenant principal do ecossistema Omnia Frigo Holding.',
  status: 'active' as const,
};
