/**
 * Dados iniciais da collection Sites — Sprint 3.
 * Sem lógica de Payload; consumido por seed/index.ts.
 */
export const sitesSeed = [
  {
    companySlug: 'omnia-frigo-holding',
    name: 'Omnia Frigo Holding',
    internalName: 'Portal Principal Omnia',
    slug: 'omnia-hub',
    type: 'holding_portal',
    siteStatus: 'active',
    environment: 'production',
    locale: 'pt-BR',
    timezone: 'America/Sao_Paulo',
    isExternal: false,
    externalUrl: undefined,
    isPrimaryForCompany: true,
    visibilityScope: 'holding',
    editorialStatus: 'approved',
  },
  {
    companySlug: 'renovacao-refrigeracao',
    name: 'Renovação Refrigeração',
    internalName: 'Site Oficial',
    slug: 'renovacao-refrigeracao',
    type: 'institutional',
    siteStatus: 'active',
    environment: 'production',
    locale: 'pt-BR',
    timezone: 'America/Sao_Paulo',
    isExternal: true,
    externalUrl: 'https://renovacaorefrigeracao.com.br/',
    isPrimaryForCompany: true,
    visibilityScope: 'company',
    editorialStatus: 'approved',
  },
  {
    companySlug: 'fred-do-frio-academy',
    name: 'Fred do Frio Academy',
    internalName: 'Site Oficial',
    slug: 'fred-do-frio-academy',
    type: 'education',
    siteStatus: 'active',
    environment: 'production',
    locale: 'pt-BR',
    timezone: 'America/Sao_Paulo',
    isExternal: true,
    externalUrl: 'https://freddofrio.com.br/',
    isPrimaryForCompany: true,
    visibilityScope: 'company',
    editorialStatus: 'approved',
  },
  {
    companySlug: 'cte',
    name: 'CTE',
    internalName: 'Site Oficial',
    slug: 'cte',
    type: 'education',
    siteStatus: 'active',
    environment: 'production',
    locale: 'pt-BR',
    timezone: 'America/Sao_Paulo',
    isExternal: true,
    externalUrl: 'https://escolacte.com.br/',
    isPrimaryForCompany: true,
    visibilityScope: 'company',
    editorialStatus: 'approved',
  },
  {
    companySlug: 'centro-educacional-sapientia',
    name: 'Centro Educacional Sapientia',
    internalName: 'Site Oficial',
    slug: 'centro-educacional-sapientia',
    type: 'education',
    siteStatus: 'active',
    environment: 'production',
    locale: 'pt-BR',
    timezone: 'America/Sao_Paulo',
    isExternal: true,
    externalUrl: 'https://centroeducacionalsapientia.com.br/',
    isPrimaryForCompany: true,
    visibilityScope: 'company',
    editorialStatus: 'approved',
  },
  {
    companySlug: 'neurofrigo',
    name: 'Neurofrigo',
    internalName: 'Site Oficial',
    slug: 'neurofrigo',
    type: 'institutional',
    siteStatus: 'active',
    environment: 'production',
    locale: 'pt-BR',
    timezone: 'America/Sao_Paulo',
    isExternal: true,
    externalUrl: 'https://neurofrigo.com.br/',
    isPrimaryForCompany: true,
    visibilityScope: 'company',
    editorialStatus: 'approved',
  },
] as const;
