/** Fixtures KI — PDF mínimo estável para pdf-parse. */

/**
 * PDF 1.4 one-page Helvetica — gerado com offsets xref validados via pdf-parse.
 * Conteúdo: "Omnia Knowledge Intelligence Seed PDF"
 */
const KI_SEED_PDF_BASE64 =
  'JVBERi0xLjQKMSAwIG9iajw8IC9UeXBlIC9DYXRhbG9nIC9QYWdlcyAyIDAgUiA+PmVuZG9iagoyIDAgb2JqPDwgL1R5cGUgL1BhZ2VzIC9LaWRzIFszIDAgUl0gL0NvdW50IDEgPj5lbmRvYmoKMyAwIG9iajw8IC9UeXBlIC9QYWdlIC9QYXJlbnQgMiAwIFIgL01lZGlhQm94IFswIDAgNjEyIDc5Ml0gL0NvbnRlbnRzIDUgMCBSIC9SZXNvdXJjZXM8PCAvRm9udDw8IC9GMSA0IDAgUiA+PiA+PiA+PmVuZG9iago0IDAgb2JqPDwgL1R5cGUgL0ZvbnQgL1N1YnR5cGUgL1R5cGUxIC9CYXNlRm9udCAvSGVsdmV0aWNhID4+ZW5kb2JqCjUgMCBvYmo8PCAvTGVuZ3RoIDY4ID4+c3RyZWFtCkJUIC9GMSAxMiBUZiA3MiA3MjAgVGQgKE9tbmlhIEtub3dsZWRnZSBJbnRlbGxpZ2VuY2UgU2VlZCBQREYpIFRqIEVUCmVuZHN0cmVhbQplbmRvYmoKeHJlZgowIDYKMDAwMDAwMDAwMCA2NTUzNSBmIAowMDAwMDAwMDA5IDAwMDAwIG4gCjAwMDAwMDAwNTYgMDAwMDAgbiAKMDAwMDAwMDExMSAwMDAwMCBuIAowMDAwMDAwMjMzIDAwMDAwIG4gCjAwMDAwMDAzMDEgMDAwMDAgbiAKdHJhaWxlcjw8IC9TaXplIDYgL1Jvb3QgMSAwIFIgPj4Kc3RhcnR4cmVmCjQxNwolJUVPRgo=';

export function buildKiSeedPdf(_text?: string): Buffer {
  void _text;
  return Buffer.from(KI_SEED_PDF_BASE64, 'base64');
}
