export {
  Counter,
  Gauge,
  Histogram,
  Registry,
  defaultRegistry,
  type MetricLabels,
} from './prometheus';
export {
  renderPrometheusMetrics,
  resetPrometheusMetricsForTests,
  httpRequestsTotal,
  httpRequestDurationSeconds,
  httpErrorsTotal,
  redisOperationsTotal,
  redisLatencySeconds,
  moodleRequestsTotal,
  moodleRequestDurationSeconds,
  moodleErrorsTotal,
  connectorCacheHitTotal,
  connectorCacheMissTotal,
  connectorActiveSessions,
  connectorRevokedSessions,
  connectorPolicyUpdates,
  connectorIdentityLinks,
  connectorHealthStatus,
  lmsStudentsOnline,
  lmsCoursesOpened,
  lmsLessonsStarted,
  lmsLessonsCompleted,
  lmsProgressRequests,
  lmsGradeRequests,
  lmsCompletionRequests,
  lmsLoginSuccess,
  lmsLoginFailure,
  lmsSessionRevocations,
  lmsPolicyChanges,
  lmsIdentityLinksMetric,
  lmsApiErrors,
} from './lms-metrics';
